version: '3.8'

services:
  postgres:
    image: postgres:13.4-buster
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    ports:
      - 7432:5432
    networks:
      priv-block-net:
        ipv4_address: 172.20.254.2

  blockscout:
    depends_on:
      - postgres
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    container_name: 'blockscout'
    links:
      - postgres:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    env_file:
      -  ./common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
        ETHEREUM_JSONRPC_HTTP_URL: http://192.168.161.25:8545/
        DATABASE_URL: postgresql://postgres:@172.20.254.2:5432/blockscout?ssl=false
    ports:
      - 4000:4000
    networks:
      priv-block-net:
        ipv4_address: 172.20.254.3

networks:
  priv-block-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.254.0/28