version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - 9091:9090
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 9092:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: always

  gethexporter:
    image: hunterlong/gethexporter
    container_name: gethexporter
    environment: 
      - GETH=http://192.168.161.25:8545
    ports:
      - 9090:9090
    restart: always